<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1.DatasetResourceName</name>
   <tag></tag>
   <elementGuidId>a600f3ce-4068-4ea4-a081-2283e11acb17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.ons-u-mb-m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Council Tax Property Attributes Data in England and Wales indexed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>be5bde62-46ff-48bb-93df-b4ec9e1f827d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ons-u-mb-m</value>
      <webElementGuid>523fe333-db84-4f7b-a1ff-3a2d5a735ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Council Tax Property Attributes Data in England and Wales indexed</value>
      <webElementGuid>0fd59132-fb46-4d09-b3bd-0213bbb29d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/h1[@class=&quot;ons-u-mb-m&quot;]</value>
      <webElementGuid>fc43b1ad-b2cf-4988-be54-96904d3419ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/h1</value>
      <webElementGuid>2b5dc3ff-23d2-4120-8f8b-80090fd06b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available data'])[2]/following::h1[1]</value>
      <webElementGuid>590b324e-329c-47fe-99ac-186499e58cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::h1[1]</value>
      <webElementGuid>2af58514-60bb-49e9-893a-532872fe90db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contents'])[1]/preceding::h1[1]</value>
      <webElementGuid>5396ef15-5244-4272-9e1f-d1f6336f59c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::h1[1]</value>
      <webElementGuid>00156f5f-6e16-4f86-8af6-39ee2d46b73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Council Tax Property Attributes Data in England and Wales indexed']/parent::*</value>
      <webElementGuid>d967041d-cd43-4491-97e4-a10811a3399c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>4042ec4d-260e-42b6-a57e-2984adbb8179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Council Tax Property Attributes Data in England and Wales indexed' or . = 'Council Tax Property Attributes Data in England and Wales indexed')]</value>
      <webElementGuid>8a6a0bdf-b9b6-45c3-ac54-ac536407d165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
