<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paragraph.Description</name>
   <tag></tag>
   <elementGuidId>8b22e7df-600c-474f-a16c-6689f76042a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.ids-u-ws-prewrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;The intended use of Valuation Office Agency Council Tax data is for house prices&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7b555572-4a29-4067-8d84-ae946155dbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ids-u-ws-prewrap</value>
      <webElementGuid>2262229f-bde8-43e7-ace1-24140b57e5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The intended use of Valuation Office Agency Council Tax data is for house prices indices and other housing statistics purposes. An initial Valuation Office Agency Stock file was delivered in July 2016 consisting of 25 million records covering the period 1st April 1993 to 1st July 2016. This was followed by monthly updates comprising of all the Billing Authorities in England and Wales. For each residential property (for which details are held) the following variables are required. Total floor area (meters squared), Number of rooms, Number of bedrooms, Property type, Postcode, Address (specifically, including house number)</value>
      <webElementGuid>81d5a379-3310-423b-bf23-7a39e8109bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details&quot;)/div[@class=&quot;ons-grid ons-grid--column@xs@s&quot;]/div[@class=&quot;ons-grid__col ons-col-8@m&quot;]/p[@class=&quot;ids-u-ws-prewrap&quot;]</value>
      <webElementGuid>980ae700-53af-4094-a472-3a56651a6eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='details']/div/div/p</value>
      <webElementGuid>c74e4bd7-0a5f-4aba-92b3-7b4cd657e42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::p[1]</value>
      <webElementGuid>d599851d-4b44-4990-8ce5-b7e7613b93a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/following::p[2]</value>
      <webElementGuid>041847c1-35a2-4ec2-b91d-8de3a443b983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About this data'])[1]/preceding::p[1]</value>
      <webElementGuid>215bae77-63ea-4e7e-9aea-4814dd20d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data creator'])[1]/preceding::p[1]</value>
      <webElementGuid>8d5f9ccb-9e87-43e1-98c3-e40046d9d205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The intended use of Valuation Office Agency Council Tax data is for house prices indices and other housing statistics purposes. An initial Valuation Office Agency Stock file was delivered in July 2016 consisting of 25 million records covering the period 1st April 1993 to 1st July 2016. This was followed by monthly updates comprising of all the Billing Authorities in England and Wales. For each residential property (for which details are held) the following variables are required. Total floor area (meters squared), Number of rooms, Number of bedrooms, Property type, Postcode, Address (specifically, including house number)']/parent::*</value>
      <webElementGuid>640a57ea-c623-4738-aab6-b4e527f9535b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>f3f491e6-1f66-424c-bd0d-e522b9dfabbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The intended use of Valuation Office Agency Council Tax data is for house prices indices and other housing statistics purposes. An initial Valuation Office Agency Stock file was delivered in July 2016 consisting of 25 million records covering the period 1st April 1993 to 1st July 2016. This was followed by monthly updates comprising of all the Billing Authorities in England and Wales. For each residential property (for which details are held) the following variables are required. Total floor area (meters squared), Number of rooms, Number of bedrooms, Property type, Postcode, Address (specifically, including house number)' or . = 'The intended use of Valuation Office Agency Council Tax data is for house prices indices and other housing statistics purposes. An initial Valuation Office Agency Stock file was delivered in July 2016 consisting of 25 million records covering the period 1st April 1993 to 1st July 2016. This was followed by monthly updates comprising of all the Billing Authorities in England and Wales. For each residential property (for which details are held) the following variables are required. Total floor area (meters squared), Number of rooms, Number of bedrooms, Property type, Postcode, Address (specifically, including house number)')]</value>
      <webElementGuid>b4aaa40f-9fa9-400d-a107-4834d5592828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
